---
abstract: 'Provides an interface to manipulate PowerDNS data in the MySQL Backend.'
author:
  - 'Augie Schwer <Augie@Schwer.us>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.113640'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PowerDNS-Backend-MySQL
no_index:
  directory:
    - t
    - inc
requires:
  DBI: 0
  Test::More: 0
version: 0.11
